//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVC_WebNgheNhac.Models.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNHAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANNHAC()
        {
            this.DANHSACHNHACs = new HashSet<DANHSACHNHAC>();
            this.TACGIAs = new HashSet<TACGIA>();
            this.THELOAIs = new HashSet<THELOAI>();
        }
    
        public int MaBanNhac { get; set; }
        public string TenBanNhac { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<int> KichThuoc { get; set; }
        public Nullable<int> DoDai { get; set; }
        public Nullable<int> TanSo { get; set; }
        public string DinhDang { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
        public string DuongDanBanNhac { get; set; }
        public string DuongDanAnh { get; set; }
        public string DuongDanTrucTuyen { get; set; }
    
        public virtual TACGIA TACGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHNHAC> DANHSACHNHACs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACGIA> TACGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THELOAI> THELOAIs { get; set; }
    }
}
