//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVC_WebNgheNhac.Models.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHNHAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHSACHNHAC()
        {
            this.BANNHACs = new HashSet<BANNHAC>();
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
        }
    
        public int MaDanhSach { get; set; }
        public string TenDanhSach { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> LuongTruyCap { get; set; }
        public string DuongDanTrucTuyen { get; set; }
        public string DuongDanAnh { get; set; }
    
        public virtual TACGIA TACGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANNHAC> BANNHACs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
    }
}
