//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVC_WebNgheNhac.Models.Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbMusicWebsiteEntities_Test : DbContext
    {
        public DbMusicWebsiteEntities_Test()
            : base("name=DbMusicWebsiteEntities_Test")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANNHAC> BANNHACs { get; set; }
        public virtual DbSet<DANHSACHNHAC> DANHSACHNHACs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<QUYENTRUYCAP> QUYENTRUYCAPs { get; set; }
        public virtual DbSet<TACGIA> TACGIAs { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
    
        public virtual int PROC_CreateDefaultRecord()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_CreateDefaultRecord");
        }
    }
}
